### ISSUE TITLE
Error trying to persist access token

### ISSUE THREAD

**Issue by zekenie** [msa7/multi_auth#3]
Hi there,

I'm new to crystal and trying to spin up an oauth client. I have it working, but I'm running into trouble persisting my `access_token`. I want to access the string property of the [`access_token`](https://crystal-lang.org/api/0.23.0/OAuth2/AccessToken.html#access_token%3AString-instance-method) string instance method and use it to pull the string out of the instance. But, because the [User class](https://github.com/msa7/multi_auth/blob/master/src/multi_auth/user.cr#L19)'s `access_token` property can be `nil`, crystal won't let me access the property `access_token` for the type `(OAuth2::AccessToken | Nil)`

Forgive me if this is a novice question.

**Comment by msa7** [comment]
I think change to

```
property access_token : OAuth2::AccessToken
```

As a workaround, you can cast type with `.not_nil!` like this `user.access_token.not_nil!.access_token`

**Comment by zekenie** [comment]
Thanks!

- Zeke
