### ISSUE TITLE
Twitter provider

### ISSUE THREAD

**Issue by veelenga** [msa7/multi_auth#4]
Are you interested in this? Would you accept such a pull request?

The problem is twitter uses OAuth 1.0 (not 2.0), but this does not violate shard name. But will need to change the interfaces though. 

https://dev.twitter.com/oauth

**Comment by msa7** [comment]
Look like Twitter support OAuth 2 for apps https://dev.twitter.com/oauth/reference/post/oauth2/token. Is it enough?

I wonder how interface will look like, in case support OAuth1?

Personally, I do not feel that OAuth1 should be supported.

**Comment by veelenga** [comment]
Unfortunately, no, it is not enough. OAuth2 used for [Application-only authentication](https://dev.twitter.com/docs/auth/application-only-auth). User-based authentication has to use OAuth 1.0a.

If you don't have plans to support 1.0, I will create a separate shard for twitter OAuth 1.0.

**Comment by msa7** [comment]
I do not have plans to massive shard API changes for support OAuth 1.0.
On another hand, If shard API changes would not big, sure I am open for PR to support Twitter provider.

**Comment by msa7** [comment]
Released https://github.com/msa7/multi_auth/releases/tag/v1.0.0
